# Generated by Django 5.0 on 2023-12-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='servico',
            field=models.CharField(max_length=15, null=True, verbose_name='Serviço'),
        ),
    ]
