# Generated by Django 5.0 on 2023-12-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orcamento_data_alter_orcamento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
