# Generated by Django 5.0 on 2023-12-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orcamento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(),
        ),
    ]
